-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1:3306
-- Tiempo de generación: 16-10-2023 a las 16:35:54
-- Versión del servidor: 5.7.40
-- Versión de PHP: 8.0.26

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `tienda_perry_el_orrintorinco`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `accounts`
--

DROP TABLE IF EXISTS `accounts`;
CREATE TABLE IF NOT EXISTS `accounts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL,
  `Pato` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `img` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

--
-- Volcado de datos para la tabla `accounts`
--

INSERT INTO `accounts` (`id`, `username`, `Pato`, `email`, `img`) VALUES
(5, 'Kazu', '$2y$15$RxqKndy3e/3ymaXJ.NIzfenBTmjmFgXzjtNxaZUI0MCQQIWrW4xW.', 'Kazu@gmail.com', 'kazu.jpg');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `torre_limitrofe`
--

DROP TABLE IF EXISTS `torre_limitrofe`;
CREATE TABLE IF NOT EXISTS `torre_limitrofe` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `catego` varchar(255) COLLATE utf8_spanish2_ci NOT NULL,
  `nombre` varchar(500) COLLATE utf8_spanish2_ci NOT NULL,
  `descr` varchar(5000) COLLATE utf8_spanish2_ci NOT NULL,
  `cant` int(11) NOT NULL,
  `precio` float NOT NULL,
  `provedor` varchar(255) COLLATE utf8_spanish2_ci NOT NULL,
  `imagen` varchar(255) COLLATE utf8_spanish2_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=42 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish2_ci;

--
-- Volcado de datos para la tabla `torre_limitrofe`
--

INSERT INTO `torre_limitrofe` (`id`, `catego`, `nombre`, `descr`, `cant`, `precio`, `provedor`, `imagen`) VALUES
(1, 'Gatos', 'Cats Best Original Arena Natural Aglutinante sin Esencia para Gato, 8.6 kg', 'Arena natural que utiliza el poder de las fibras de madera para absorber eficazmente los líquidos y el mal olor, Cats Best está hecho exclusivamente con materias primas renovables sostenibles y biodegradables con un sobresaliente poder aglutinante. ', 50, 829, 'Cats Best', 'one.jfif'),
(2, 'Gatos', 'Hills Science Diet Alimento Seco para Gato Adulto Receta Pollo, 7.3 kg', 'El alimento seco para gatos Hills Science Diet Adult está especialmente formulado para abastecer las necesidades de energía de los gatos durante la mejor etapa de sus vidas. Hecho con ingredientes de alta calidad, fáciles de digerir.', 50, 1253.55, 'Hills Science', 'two.jfif'),
(3, 'Gatos', 'Royal Canin Alimento Seco para Gato Adulto de Interior Receta Pollo, 3.1 kg', 'Indoor Adult de Royal Canin es un alimento especial para gatos adultos de interior a partir de 1 año de edad. Mejora la digestibilidad del alimento en el tracto intestinal del gato reduciendo con esto la presencia de malos olores fecales, todo esto gracias a la adición de zeolita, proteínas de alta digestión, pulpa de remolacha y FOS.', 50, 765, 'Royal Canin', 'three.jfif'),
(4, 'Gatos', 'You & Me Mueble para Gato Tipo Árbol de 7 Niveles con Juguete y Rascador de Cartón', 'El árbol para gato de 7 niveles You & Me cumple con los deseos de tu mejor amigo gatuno de jugar, descansar y rascar con una variedad de texturas y formas agradables. El juguete colgante móvil en esta pieza de mobiliario para gatos los entretiene y los tienta a saltar y divertirse, mientras que los postes de sisal y el panel de rascador de cartón satisfacen sus necesidades de rascar y afilar sus garras.', 30, 422.25, 'You & Me', 'four.jpg'),
(5, 'Perros', 'Seresto Collar Antipulgas y Garrapatas para Perro y Gato, Chico', 'El collar Seresto de Bayer acaba con las pulgas de tu mascota y sus larvas del entorno, y repele y elimina las garrapatas. Seresto es distinto de los collares convencionales contra pulgas y garrapatas. Utiliza una novedosa combinación de materiales que permite la liberación controlada de dosis adecuadas de los principios activos hasta 8 meses. Esto confiere una excelente protección de tu mascota, no solo porque mata las pulgas y garrapatas, sino también porque repele las garrapatas antes de que le lleguen a picar e ingerir sangre, lo que ayuda a proteger a tu mascota de las enfermedades que estos parásitos pueden transmitir.', 80, 748.3, 'Bayer', 'five.jfif'),
(6, 'Gatos', 'Feliway Classic Spray con Efecto Calmante para Gato, 60 ml', 'Los gatos son unos animales que se estresan con facilidad ante situaciones desconocidas. El comportamiento agresivo, el marcaje con arañazos u orina, la falta de apetito o la insaciabilidad, el exceso de acicalamiento y la disminución del juego y de la interacción son algunas señales de que el gato está estresado. El análogo de la feromona facial felina de Feliway ayuda a calmar a tu gato y a sentirse bien en situaciones de estrés. El spray Feliway se puede usar en situaciones muy especiales, tales como las visitas al veterinario, en la transportadora o si el gato marca territorio mediante la orina o los arañazos en zonas puntuales.', 50, 842.8, 'Feliway', 'six.jfif'),
(7, 'Gatos', 'Advantage Multi Pipeta Antiparasitaria Interna y Externa para Gato, 4 a 8 kg', 'Advantage Multi Gatos protege a los gatos por dentro y por fuera. Provee protección integral contra pulgas, gusano del corazón, lombrices intestinales, gusanos pulmonares, ácaros de la sarna de la oreja y ácaros de la sarna felina con un tratamiento de aplicación tópica y fácil de utilizar que se aplica una vez al mes.', 57, 506.3, 'Bayer', 'seven.jfif'),
(8, 'Perros', 'Inobazz Megatrol Talco Antiparasitario Externo para Perro y Gato, 80 g\n140139', 'Megatrol Talco es un ectoparasiticida que ayuda a controlar y eliminar eficazmente las infestaciones causadas por pulgas, garrapatas y ácaros, con un efectivo efecto parasiticida y un amplio margen de seguridad el talco antiparasitario es sugerido para usarse de manera externa sobre la mascota y también para utilizarse sobre las superficies que frecuentan los animales de compañía o sus accesorios tales como camas o tapetes, cuenta con un efecto residual que permanecerá por varios días y además, es un producto ecológico y sustentable. Para un control amplio y prolongado de ectoparásitos se sugiere implementar una estrategia integral.\n\n', 50, 129, 'Inobazz ', 'eight.jfif'),
(9, 'Gatos', 'Hills Science Diet Healthy Cuisine Alimento Húmedo para Gato Adulto Receta Pollo Rostizado y Arroz, 80 g', 'Un gato sano es un gato feliz. Cuando le sirve a su mascota consentida el alimento húmedo para gatos Hills Science Diet Healthy Cuisine Receta de pollo y arroz, tiene las dos cosas. Nuestro alimento para gatos está hecho en los EUA con ingredientes importados. Con esta deliciosa mezcla de trocitos de pollo, arroz tierno y sabrosos vegetales, el alimento enlatado para gatos Healthy Cuisine es un alimento que encantará a su gato. Los alimentos enlatados para gatos Science Diet proporcionan el balance perfecto de sabor y nutrición, y no contienen sabores o conservadores artificiales.', 80, 0, 'Bayer', 'nine.jfif'),
(10, 'Gatos', 'Leaps & Bounds Paquete 4 Pelotas Enrejadas Multicolor para Gato, 1 Paquete', 'Encuentra el juguete adecuado para tu gatito que combine su personalidad, hábitos y estilo de vida. Nuestras pelotas enrejadas Leaps & Bounds resuenan mientras ruedan gracias al cascabel interior que tintinea al moverse. Perfectas para cualquier gato al que le guste hacer ruido. Tu gato se divertirá durante horas golpeando, acechando y persiguiendo. Estas pelotitas son una excelente manera de garantizar que tu gatito haga mucho ejercicio saludable en forma de diversión.', 80, 95.06, 'Leaps & Bounds', 'ten.gif'),
(11, 'Gatos', 'Leaps & Bounds Pescadito con Largas Plumas Colores Variados, 1 Pieza', 'El pescadito con plumas y hierba gatera Leaps & Bounds es el compañero de juegos perfecto para cualquier gatito. Esta adorable y pequeña criatura está cubierta con una tela de malla para una apariencia auténtica de escamas de pescado. Las plumas de avestruz en las aletas y la cola combinan plumas suaves y tenues para atraer a tu gatito a horas de juego.', 80, 103.25, 'Leaps & Bounds', 'twelve.jfif'),
(12, 'Perros', 'Pro Plan Optiage Active Mind Alimento Seco para Perro Senior Raza Mediana/Grande Receta Pollo y Arroz, 13 kg', 'Pro Plan Optiage Active Mind prolonga la vitalidad de tu perro mayor de 7 años al brindarle una nutrición avanzada que le ayudará a retrasar los signos de envejecimiento manteniéndolo sano y activo. Croquetas con una proporción equilibrada de proteína y grasa para mantener la masa muscular magra, una combinación de antioxidantes naturales y vitaminas E y C.', 80, 2, 'Pro Plan Optiage Active ', 'therteen.jfif'),
(13, 'Perros', 'Precision Pet Cabina Extreme Outback Casa de Exterior para Perro, Grande', 'La casa para exterior Extreme Outback es el refugio perfecto al aire libre para tu perro. Construido con madera maciza y herrajes de acero inoxidable lo hacen extremadamente resistente. Con forma de cabaña tradicional, sus patas nivelables y resistentes a la intemperie permiten que la estructura se equilibre incluso en superficies rugosas. Meticulosamente diseñada, esta casa para perros también cuenta con un techo de tejas de asfalto resistente a la lluvia para una mayor protección para su mascota contra los elementos climáticos.', 100, 5, 'Precision Pet', 'fourteen.jfif'),
(14, 'Perros', 'Petmate Índigo Casa de Exterior para Perro, Mediano', 'La casa para perros Petmate Índigo en forma de iglú es una opción robusta y espaciosa que brinda seguridad y comodidad a tu perro. Con un marco de puerta extendida le brinda a tu mascota protección adicional contra la lluvia y el viento. El diseño patentado de la cúpula mantiene la casa estable en vientos fuertes y al mismo tiempo desliza la nieve y otros escombros que podrían acumularse en la parte superior. La casa presenta una construcción resistente que mantiene a las mascotas frescas en verano y cálidas en invierno. La ventilación superior permite un flujo de aire continuo. El marco de piso elevado para mantener el interior seco.', 100, 2, 'Petmate', 'fiveteen.jfif'),
(15, 'Perros', 'Good2Go Arnés de Malla Ajuste Romano Doble Argolla Color Rojo para Perro, Mediano', 'El arnés de malla para perros Good2Go cuenta con una capa de malla transpirable y un acojinado liviano para que se pueda garantizar la comodidad de tu cachorro durante sus caminatas diarias. Para lograr un ajuste perfecto, simplemente ajuste la cinta en un sencillo paso.', 50, 414.4, 'Good2Go', 'sixteen.jfif'),
(16, 'Perros', 'Kurgo Plato Colapsable de Silicón para Perro Color Rojo 124650', 'El plato plegable KURGO es ideal para llevarlo en las mochilas o transportadoras de tela pero ideal para una ración de delicioso alimento o agua. Al ser de silicón se puede lavar sin problemas lo que lo vuelve un accesorio indispensable en los paseos o viajes cortos.', 50, 414.4, 'Kurgo', 'seventeen.jfif'),
(17, 'Perros', 'Livelong Healthy & Strong Alimento Natural Húmedo para Perro Todas las Edades Receta Cordero/Res/Camote, 354 g', 'Livelong Healthy & Strong Cordero con res y camote es un alimento 100% natural para perros con 90% carne de cordero y res. Contiene además camote y vegetales orgánicos. No contiene granos de ningún tipo. Proteína de alta digestibilidad que provee todos los aminoácidos esenciales. Para agregar valor nutricional y una mejor fuente de proteínas, combinamos nuestra receta de res con cordero y también con hígado, ya que es una excelente fuente de vitaminas y hierro.', 100, 192.2, 'Livelong Healthy & Strong', 'eightteen.jfif'),
(18, 'Perros', 'Canine Chews Carnaza Twist con Tiras de Pollo para Perro, 20 Piezas', 'Livelong Healthy & Strong Cordero con res y camote es un alimento 100% natural para perros con 90% carne de cordero y res. Contiene además camote y vegetales orgánicos. No contiene granos de ningún tipo. Proteína de alta digestibilidad que provee todos los aminoácidos esenciales. Para agregar valor nutricional y una mejor fuente de proteínas, combinamos nuestra receta de res con cordero y también con hígado, ya que es una excelente fuente de vitaminas y hierro.', 80, 200, 'Canine Chews', 'nineteen.jfif'),
(19, 'Perros', 'Livelong Healthy & Strong Alimento Natural HÃºmedo para Perro Todas las Edades Receta Pollo/Camote, 354 g', 'Livelong Healthy & Strong Pollo y Camote es un alimento 100% natural para perros con 90% carne de pollo. Contiene ademÃ¡s camote y vegetales orgÃ¡nicos. No contiene granos de ningÃºn tipo. ProteÃ­na de alta digestibilidad que provee todos los aminoÃ¡cidos esenciales. Para agregar valor nutricional y una mejor fuente de proteÃ­nas, combinamos nuestra receta de pollo con pavo y tambiÃ©n con hÃ­gado de pollo, ya que es una excelente fuente de vitaminas y hierro.', 50, 105, 'Livelong Healthy & Strong', 'twenty.jfif'),
(20, 'Gatos', 'Youly Collar con Broche DiseÃ±o Bandana a Rayas para Gatito, Multicolor', 'El collar para gatos con broche de seguridad de la marca Youly cuenta con un atractivo diseÃ±o con bandana a rayas multicolor que harÃ¡ lucir elegante e increÃ­ble a tu gatito. Su ajuste es ideal para mantener cÃ³modo a tu amigo felino. Teniendo en mente la curiosidad de los felinos y los lugares en los que suelen jugar, cuenta con un broche de seguridad que libera al gato en caso de que se atore.', 50, 125, 'YOULY', 'twentyone.jfif'),
(21, 'Peces', 'Tetra Color Alimento en GrÃ¡nulo para Peces Tropicales, 300 g', 'Tetra Color es un alimento diseÃ±ado para promover naturalmente los hermosos colores de los peces tropicales mÃ¡s grandes como el disco y el pez Ã¡ngel. Los grÃ¡nulos de tamaÃ±o mediano, que se hunden lentamente, diseÃ±ados para brindar nutriciÃ³n que mejora el color tambiÃ©n a los alimentadores de fondo. Vitamina c enriquecida. *Aviva los colores de los peces tropicales*Aporta nutrientes indispensable*Adicionado con con vitamina C*Contiene ProCare', 100, 374.4, 'Tetra', 'twentytwo.jfif'),
(22, 'Peces', 'Tetra Acuario Led Kit Stay Clean, 132 L', 'El acuario de cristal, es resistente a rayones por lo cual serÃ¡ muy perdurable. Cuenta con campanas led de bajo consumo que crean un efecto de brillo natural. Su diseÃ±o con tapa negra es sencillo pero con apariencia elegante. NotarÃ¡s una ventanilla de alimentaciÃ³n ademÃ¡s que tiene bisagras que ayudan a su fÃ¡cil manejo a la hora del mantenimiento. Te sorprenderÃ¡ el contenido de este kit; sistema de filtraciÃ³n Whisper 30, un calentador, termÃ³metro, red y una muestra de alimento y acondicionador de agua, ademÃ¡s de GuÃ­as de configuraciÃ³n y cuidado.', 100, 4450, 'Tetra', 'twentythree.jfif'),
(23, 'Peces', 'Glofish Acuario Glo Kit, 37.8 L', 'El Kit de acuario GloFish de 37.8 litros, contiene todo lo necesario para comenzar con una gran experiencia GloFishÂ®. Perfecto para quienes inician en el mundo de la acuariofilia como para expertos, este kit completo cuenta con un acuario de cristal, sistema de iluminaciÃ³n LED, capucha y filtro de potencia TetraÂ® Whisper PF10 con cartucho de filtro TetraÂ® WhisperÂ®Â® Bio-BagÂ® mediano para ayudarlo a crear un entorno agradable para sus peces fluorescentes GloFish. Este acuario cobra vida con las luces LED GloFish de bajo consumo azul y blanca. Elija entre el modo de luz de luna con todas las luces azules encendidas o el modo de luz solar con todas las luces encendidas. La tapa o dosel reduce la pÃ©rdida de agua por evaporaciÃ³n y ayuda a evitar que los peces salten. El filtro de potencia Tetra Whisper proporciona una combinaciÃ³n efectiva de filtraciÃ³n mecÃ¡nica, quÃ­mica y biolÃ³gica para agua limpia y peces sanos.', 60, 2990, 'Glofish', 'twentyfour.jfif'),
(24, 'Peces', 'Seachem Matrix, 250 ml', 'Medio filtrante biolÃ³gico de alta capacidad que elimina eficazmente amonÃ­aco Nitrito y Nitrato', 60, 205, 'Seachem', 'twentyfive.gif'),
(25, 'Peces', 'Tetra Cichlid Alimento en Sticks para CÃ­clidos, 320 g', 'Dieta equilibrada desde el punto de vista nutricional para cÃ­clidos. La alta digestibilidad de los sticks promueve agua clara, reduciendo al mÃ­nimo los residuos. Mejora el color y promueve la vitalidad de tus peces. Su fÃ³rmula favorece un buen funcionamiento del sistema inmune, para una Ã³ptima salud y una larga vida. Contenido de 320 gr *Ricos en proteÃ­nas*CientÃ­ficamente desarrollados', 30, 387.6, 'Tetra', 'twentysix.jfif'),
(26, 'Peces', 'Azoo 11 en 1 Bio-Bacteria para Acuario, 250 ml', 'AZOO 11 en 1 Super Bio-Bacteria aporta al acuario un gran nÃºmero de ventajas. Contiene cepas de bacterias Bacillus sp. de gran calidad que aportan una rÃ¡pida descomposiciÃ³n de sustancias orgÃ¡nicas tÃ³xicas como el amonÃ­aco y el nitrito. A su vez, tambiÃ©n inhibe elcrecimiento de otras bacterias patÃ³genas ayudando asÃ­ a la prevenciÃ³n de enfermedades. Por otro lado, las cepas de Lactobacillus sp. y Streptococcus sp. junto con la levadura que contiene ayudan a mejorar la digestiÃ³n de los peces y evitan enfermedades en el tracto digestivo. Las cepas de Aspergillus sp. y los hongos que incluye su fÃ³rmula son Ãºtiles en el procesamiento metabÃ³lico de los carbohidratos en la dieta de los peces disminuyendo la contaminaciÃ³n orgÃ¡nica en el agua. Por otro lado, el extracto de yuca elimina eficazmente el amonÃ­aco, el nitrito y el sulfuro de hidrÃ³geno del agua mejorando la salud de los peces y disminuyendo su estrÃ©s. Por Ãºltimo, las enzimas que contiene AZOO 11 in 1 Super Bio-Bacteria son Ãºtiles en el refuerzo de la capacidad de descomposiciÃ³n de los microbios, mejora la digestiÃ³n de los peces y reduce la cantidad de materia orgÃ¡nica de deshecho en el agua del acuario.', 60, 315, 'Azoo', 'twentyseven.jfif'),
(27, 'Peces', 'Tetra Whisper 10I Filtro Interno para Acuario, 37 L', 'El filtro de acuario interno Tetra Whisper es lo Ãºltimo en filtraciÃ³n silenciosa y conveniente de 3 etapas. La malla de doble cara del Bio-BagÂ® los desechos, mientras que el carbÃ³n activado absorbe los olores y la decoloraciÃ³n. La filtraciÃ³n biolÃ³gica es proporcionada por el Bio-Scrubber. El diseÃ±o antiatascamiento de Bio-Scrubber proporciona una filtraciÃ³n biolÃ³gica completa con la comodidadde menos mantenimiento. Debido a que el Bio-Scrubber tiene una parte posterior sÃ³lida, el agua se ve forzada a fluir uniformemente sobre las cerdas ricas en bacterias. *El filtro es sumergible.', 150, 445, 'Tetra', 'twentyeight.jfif'),
(28, 'Peces', 'Tetra Bio-Bag Cartucho para Filtro Desechable Mediano, 8 Piezas', 'Los respuesto para filtro Bio Bag contiene carbÃ³n ultra activado que absorbe los olores y la decoloraciÃ³n, de manera mÃ¡s efectiva que otras marcas. La malla densa de dos lados captura los desechos de los peces. Fabricado con mÃ¡s mallas para capturar otros desechos. Contiene 8 piezas *Elimina los olores*Evita la decoloraciÃ³n', 31, 325, 'Tetra', 'twentynine.jfif'),
(29, 'Peces', 'Tetra Life Guard Tratamiento para Acuario de Agua Dulce, 32 Tabletas', 'Lifeguard es un tratamiento de amplio espectro que trata enfermedades en peces de agua dulce. La acciÃ³n de Life Guard ataca y destruye los microorganismos que causan enfermedades. Cada dosis trata enfermedades infecciosas como hongos, rayas rojas, limo lechoso o desmenuzado, gripe, enfermedad de las branquias bacterianas, podredumbre de la boca y de las aletas, aletas fijas o rasgadas y Ãºlceras. TambiÃ©n se puede usar como preventivo cuando se agregan nuevos peces a un acuario establecido. Contenido 32 tabletas *FÃ¡cil de usar*Destruye microganismos', 35, 235, 'Tetra', 'thirty.jpeg'),
(30, 'Peces', 'Zoo Med Hamaca de Descanso para Betta, 1 Pieza', 'El descanso es una parte importante del desarrollo y crecimiento de cualquier especia animal: marina o terrestre. Tu pez Betta tambiÃ©n debe descansar apropiadamente para continuar optimamente con su ciclo de vida. La Hamaca de descanso Zoo Med estÃ¡ diseÃ±ada especialmente para ofrecer a tu mascota un lugar de descanso apropiado. Cuenta con un diseÃ±o de hoja que simula los elementos de su hÃ¡bitat natural, ayÃºdandolo a sentirse como en su ambiente natural. Este artÃ­culo contiene una ventosa para su fijaciÃ³n en cualquier parte de tu acuario *Permite que tu Betta descanse cerca de la superficie del agua tal como lo hacen en la naturaleza*Se sujeta al recinto Betta con ventosa (incluida)', 64, 55, 'Zoo Med', 'thirtyone.jfif'),
(31, 'Peces', 'Penn Plax Casa Calamardo Cabeza, 7.62 cm Largo x 7.62 cm Ancho x 15 cm Alto', 'Este es un adorno divertido. El Penn Plax Casa Calamardo agregarÃ¡ diversiÃ³n en la isla a cualquier acuario.EstÃ¡ hecho de resina no tÃ³xica. La decoraciÃ³n proporciona refugio y escondites que los peces necesitan para ayudar a reducir el estrÃ©s.', 51, 260, 'Penn Plax', 'thirtytwo.gif'),
(32, 'Aves', 'You & Me Hábitat Vertical para Loro, Grande', 'Proporciona a tu ave suficiente espacio para jugar con la jaula vertical de YOU & ME. La espaciosa jaula de aves de You & Me es ideal para aves medianas y grandes, esta jaula le brindara a tu amigo con plumas el espacio suficiente para jugar, posarse, estirar sus alas y moverse libremente dentro y fuera de ella.', 45, 7899, 'You & Me', 'thirtythree.jfif'),
(33, 'Aves', 'Versele-Laga Prestige Alimento de Semillas para Ninfas y Agapornis, 4 kg', 'La mezcla Versele-Laga PRESTIGE contiene una gran variedad de semillas de diferentes tamaÃ±os y texturas que atraerÃ¡n y estimularÃ¡n el apetito en ninfas agapornis y otros psitÃ¡cidos medianos. Contiene los nutrientes esenciales para que tus aves estÃ©n saludables y lejos de complicaciones veterinarias. Les proporciona a sus aves una dieta equilibrada compuesta por diferentes semillas verduras y vitaminas. Contenido 4 Kg.', 60, 520, 'Versele-Laga', 'thirtyfour.jfif'),
(34, 'Aves', 'You & Me Zona de Juegos 3 en 1 para Ave', 'El gimnasio de juegos estÃ¡ diseÃ±ado para aves y tiene tres Ã¡reas diferentes para que el aves juegue y haga ejercicio. El gimnasio de juegos incluye una escalera, un columpio y un Ã¡rea de alimentaciÃ³n. Se recomienda para avess de tamaÃ±o pequeÃ±o a mediano, como periquitos, agapornis y cotorras. Los clientes pueden comprar el producto en lÃ­nea o en la tienda.', 85, 580, 'You & Me', 'thirtyfive.jfif'),
(35, 'Aves', 'Stokes Wildbird Bebedero Mason Jar para ColibrÃ­', 'Stoke Wildbird Bebedero ColibrÃ­ Mason Jar es un artÃ­culo de decoraciÃ³n del jardÃ­n que permite atraer colibrÃ­es para tu deleite y ademÃ¡s les brinda a ellos la posibilidad de recuperar energÃ­as para seguir su vuelo. E Se puede colocar en las ramas de los Ã¡rboles o cerca de alguna ventana para que puedas observarlos de cerca. Al principio los colibrÃ­es pueden ser tÃ­midos y no acercarse pero con el tiempo descubren el nÃ©ctar y confÃ­an en la comida que le estÃ¡s poniendo.', 65, 669, 'Stokes Wildbird', 'thirtysix.jfif'),
(36, 'Aves', 'Sophresh Cama de Papel Desmenuzado para Aves, 20 L', 'Papel reciclado que absorbe la humedad de la jaula de sus aves, tiene poco polvo y bicarbonato de sodio para un excelente control de olores. Sin productos quÃ­micos aÃ±adidos.', 54, 329, 'Sophresh', 'thirtyseven.jfif'),
(37, 'Aves', 'You & Me Transportadora para Ave Color Dorado', 'La transportadora You & Me para ave estÃ¡ diseÃ±ada para una fÃ¡cil transportaciÃ³n de tu mejor amigo. Ãšnica en el mercado y pensando en las necesidades de las aves incluye una percha y ranura para fÃ¡cil alimentaciÃ³n. Tu mejor amiga se sentirÃ¡ segura y protegida para menor estrÃ©s en el viaje ya sea al veterinario, mudanza entre otros viajes.', 42, 450, 'You & Me', 'thirtyeight.jfif'),
(38, 'Aves', 'Ecos Limpiador EnzimÃ¡tico para Jaulas, Transportadoras y HÃ¡bitats de Mascotas, 650 ml', 'Ecos Limpiador EnzimÃ¡tico para jaulas y habitas elimina manchas y olores al contacto. Ya sea que tenga un ave alegre, un cachorro que adore viajar o un conejito esponjoso, tenemos el limpiador de jaulas perfecto para ti. Hecho con enzimas que descomponen y eliminan manchas, suciedad y olores, el limpiador de jaulas Ecos funciona para todo tipo de jaulas, incluyendo vidrio, metal, acrÃ­lico, plexiglÃ¡s y mÃ¡s. AutÃ©ntico, sustentable y accesible.. Â¡asÃ­ es Ecos!', 64, 280, 'Ecos', 'thirtynine.jfif'),
(39, 'Aves', 'Krukets Premios para Ninfa y Agaporni, 90 g', 'Krukets Ninfa & Agaporni 90 g, barritas crujientes con semillas, granos y pellets que proporcionan una nutriciÃ³n balanceada y saludable. Su forma compacta evita el desperdicio ademÃ¡s permite dar variedad a la dieta de su ave y proporciona entretenimiento.', 32, 75, 'Krukets', 'forty.jfif'),
(40, 'Aves', 'You & Me Soporte de Jibia-Mijo para Aves, Chico', 'El sujetador o Porta premios You & Me, permite colocar golosinas como el mijo al hÃ¡bitat de su ave, y ayuda a prevenir la dispersiÃ³n de fragmentos de jibia por el hÃ¡bitat. Tiene una construcciÃ³n duradera, fÃ¡cil de limpiar y un soporte universal para poder instalarlo en todo tipo de hÃ¡bitat', 21, 50, 'You & Me', 'fortyone.jfif'),
(41, 'Aves', 'You & Me Bebedero Tipo Silo para Ave, 15 cm', 'Nuestro bebedero de cristal en forma de silos de you and me, le encantarÃ¡n a tus aves. Se sujeta de manera segura a las rejas de las jaulas verticales. El barril de vidrio transparente hace que sea fÃ¡cil de controlar el nivel de agua, es higiÃ©nico y fÃ¡cil de limpiar. La base es de plÃ¡stico.', 54, 39, 'You & Me', 'fortytwo.jfif');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
